from __future__ import annotations

import json
import sys
from pathlib import Path

import browser_cookie3


def load_config() -> dict:
    config_path = Path("config.json")
    if not config_path.exists():
        print("[!] config.json not found, using defaults (edge)")
        return {"cookies_from_browser": "edge"}
    
    with open(config_path, "r", encoding="utf-8") as f:
        return json.load(f)


def sync_cookies(output_path: str = "streamer_cookies.txt") -> bool:
    config = load_config()
    browser_name = config.get("cookies_from_browser", "edge").lower()
    
    print(f"[*] Trying to extract Chaturbate cookies from {browser_name.capitalize()}...")
    
    try:
        # Resolve the browser_cookie3 loader dynamically, for example edge/chrome/firefox.
        if hasattr(browser_cookie3, browser_name):
            browser_func = getattr(browser_cookie3, browser_name)
            cookies = browser_func(domain_name="chaturbate.com")
        else:
            print(f"[!] Browser '{browser_name}' is not supported by browser_cookie3.")
            return False
        
        # Convert to the Netscape cookie format expected by yt-dlp.
        with open(output_path, "w", encoding="utf-8") as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# This file is generated by Streamer-DVR Sync script. Do not edit.\n\n")
            
            count = 0
            for cookie in cookies:
                # Keep only cookies relevant to the target platform.
                if "chaturbate.com" in cookie.domain:
                    secure = "TRUE" if cookie.secure else "FALSE"
                    flag = "TRUE" if cookie.domain.startswith(".") else "FALSE"
                    expiration = str(cookie.expires or 0)
                    
                    line = f"{cookie.domain}\t{flag}\t{cookie.path}\t{secure}\t{expiration}\t{cookie.name}\t{cookie.value}\n"
                    f.write(line)
                    count += 1
            
            if count > 0:
                print(f"[+] Successfully extracted {count} cookies to {output_path}")
                return True
            else:
                print(f"[!] No cookies found for chaturbate.com in {browser_name}.")
                return False
            
    except Exception as e:
        print(f"[!] Error: {str(e)}")
        if "KeyChain" in str(e) or "Safe Storage" in str(e):
            print("[!] MacOS Security Alert: Please run this script MANUALLY in your terminal once")
            print("[!] and click 'Always Allow' when asked for KeyChain access.")
        return False


if __name__ == "__main__":
    if sync_cookies():
        sys.exit(0)
    else:
        sys.exit(1)
